### ISSUE TITLE
Footer: Add banner

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/tally.cash#109]
We need to add powered by Alchemy to the footer.

### Preview
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/80846886/192554951-26a8f399-86ac-465c-9d7e-689d823cee84.png">

### File
![badgeLight](https://user-images.githubusercontent.com/80846886/192555115-d95f24bc-e2b8-4783-b642-fac74abb57bc.png)

### Specs

194x42, center :)

**Comment by puppycodes** [comment]
There's some distinct styling differences between ur image and the current footer state, am I just approximating from this and adding: powered by alchemy and good hunting! ?
<img width="379" alt="Screen Shot 2022-10-03 at 12 10 05 PM" src="https://user-images.githubusercontent.com/5248271/193659022-05cceded-4a56-4968-8c2c-9cf39b6ccf7f.png">

**Comment by puppycodes** [comment]
for ref:
![diff-footer](https://user-images.githubusercontent.com/5248271/193659901-6586330b-345b-4dbd-a9b1-871298d99a03.png)

**Comment by VladUXUI** [comment]
yeah, looks like the footer was never updated to the designs from Gluzman.

If you can do the changed to the footer that would be good. If not, then we can just approximately place the Powered by Alchemy image under Logo/Tally Ho! and we can update footer later

**Comment by VladUXUI** [comment]
Here is a [link to the footer](https://www.figma.com/file/eT5hwXGEM1gKasupZMepLK/Tally-Website?node-id=2333%3A77999), just in case.

Sorry for the mix-up, didn't notice it wasn't updated

**Comment by puppycodes** [comment]
awesome! will do it all!
