### ISSUE TITLE
Please use Zulip instead of closed source Discord for user generated communication

### ISSUE THREAD

**Issue by labeldevops** [tallycash/tally.cash#32]
I would like to propose to use the much better zulip.com chat instead of the inferior Discord. 

Not only has it much better features, also it is open source and allows total control of user generated content - while Discord is a gatekeeper and owns and potentially stops distribution of valuable user content without you having control over it. 

Discord practices authoritarian censorship right from the beginning - e.g. it does not like the email address that I want to use with it and so I can not login and write things. Think about it for a minute - the first user interaction is based on brutally disallowing me to use the "wrong" kind of email service - censorshop right at the front door - totally inacceptable for a project that promotes user freedom with the appropriate source code licenses.

Also Discord GUI is really primitive compared to Zulip.

Please leave that service, use free (for open source) Zulip or consider maintaining your own Zulip servers.

**Comment by mhluongo** [comment]
Hey @labeldevops, thanks for the feedback! As an open source advocate, I understand where you're coming from. As a community person, though, I strongly disagree with this one on two fronts.

1. We go where our users are. We have 10k community members on Discord. I've never seen a project in our category come close to that on Zulip... or Element, or Keybase back in the day, or a variety of other values-aligned options I can think of. You are welcome to build out a Zulip server, but I don't expect many will be familiar with the project or comfortable switching tools. I'd love to be wrong here.

2. If you want us to change chat venues... build consensus with the community! We have a forum at [gov.tally.cash](https://gov.tally.cash) where you can build your case and convince others to come along.

I strongly agree with the ideological point you're trying to make, especially around censorship resistance. But as a long-time Linux fan and crypto dev, my experience is that passionate pleas don't change community direction. **Action does.**

**Comment by mhluongo** [comment]
Note I'd also be happy to help bridge a Zulip or Matrix client community chat to the Discord server. I want to support this and keep our chat accessible, I just don't plan to do it through force.

Leaving this open for a bit for discussion, then planning to close as `wontfix`.
