### ISSUE TITLE
Firefox addon seems to be missing

### ISSUE THREAD

**Issue by cmroanirgo** [tallycash/tally.cash#36]
The Firefox extension link seems to be broken.

The website has two links to: https://addons.mozilla.org/en-US/firefox/addon/tally/ as the place to get tally community edition. The page returns a 404 Not Found.

**Comment by cairomassimo** [comment]
@cmroanirgo thanks for the report. We are aware of this, and we are trying to fix this issue ASAP.

@mr-michael should we hide the link on the website until resolved?

**Comment by mhluongo** [comment]
This has been fixed for a bit!
