### ISSUE TITLE
Tally Ho! Rebrad

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#46]
We've got to rebrand by EOD today Thursday Mar 10!

Updated logos are available here: https://www.figma.com/file/pivdyhpBD2FQGej6ToRSdA/?node-id=0%3A1 

They look like this: 

<img width="595" alt="Screen Shot 2022-03-09 at 8 50 10 PM" src="https://user-images.githubusercontent.com/7005061/157572277-5fbee332-531a-4220-af77-5dae6c9964d3.png">

**Header**
![image](https://user-images.githubusercontent.com/7005061/157572190-8beba6e3-ff19-4932-b658-7dac6d8ef97d.png)

Let's plz update current image with this design from Figma:

<img width="227" alt="Screen Shot 2022-03-09 at 8 51 41 PM" src="https://user-images.githubusercontent.com/7005061/157572446-21fb9657-5819-4e9c-9f0f-b57c0f1194c8.png">

**Footer**

<img width="831" alt="Screen Shot 2022-03-09 at 8 51 09 PM" src="https://user-images.githubusercontent.com/7005061/157572468-8a65d53e-030d-4138-b31c-a762b042ecd5.png">

Can we please add this disclaimer below the nav items and above the copyright notice: "The TallyHo Wallet is not affiliated with dAppHero and/or the Tally voting dashboard and blockchain governance platform at http://withtally.com."

**https://tally.cash/**
- All "Tally" --> "Tally Ho"
- Except: "Tally is the first Web3 wallet that’s owned by its users." --> "Tally Ho! The first Web3 wallet that’s owned by its users."

**https://tally.cash/community-edition**
- All "Tally" --> "Tally Ho"
- Except: "Get the Tally Wallet Community Edition" --> "Tally Ho! Community Edition"

**https://tally.cash/privacy & https://tally.cash/ccpa/**
- All "Tally" or "Tally Wallet" --> "Tally Ho"
- For example: "At **Tally Wallet** (collectively referred to as “**Tally**”, “we”, “us” or “our”), we respect your privacy and are committed to protecting it." --> "At **Tally Ho** (collectively referred to as “**Tally Ho**”, “we”, “us” or “our”), we respect your privacy and are committed to protecting it. "
- "This notice covers all personal information collected in the use of this website, as well as any other websites, applications including **Tally Wallet** web browser extension" --> "This notice covers all personal information collected in the use of this website, as well as any other websites, applications including **the Tally Ho** web browser extension,"
- "**Tally** is the controller and responsible for your personal data." --> "**Tally Ho** is the controller and responsible for your personal data."

**Comment by VladUXUI** [comment]
![TallyHo_Logo](https://user-images.githubusercontent.com/80846886/157604243-0ba0b5a9-b46f-431f-ab5b-f5afcb7b6e44.svg)
Attaching the SVG logo
