### ISSUE TITLE
Update meta image

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#49]
Still displays as "Tally"
<img width="361" alt="Screen Shot 2022-03-17 at 4 06 49 PM" src="https://user-images.githubusercontent.com/7005061/158888278-aa7be368-23d1-4854-aaef-c09b09cd7ed1.png">

**Comment by VladUXUI** [comment]
![Tally_Ho_website](https://user-images.githubusercontent.com/80846886/159031748-35c4385f-6e68-4bf0-ac0e-36bfeba2f50f.png)

**Comment by cairomassimo** [comment]
Will be fixed as part of https://github.com/tallycash/tally.cash/issues/75.
