### ISSUE TITLE
Petition - Update middle section of homepage

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#61]
Link to figma: https://www.figma.com/file/eT5hwXGEM1gKasupZMepLK/Tally-Website?node-id=2823%3A85779

The main change is adding the NFT section! There are also small copy changes throughout this section.

Only part of the page that needs to change is the part in this screenshot:

<img width="417" alt="Screen Shot 2022-08-08 at 9 31 26 PM" src="https://user-images.githubusercontent.com/7005061/183543271-81f0e986-100e-4865-bd0c-ccfafc79085b.png">

We also want to add a large button letting people know about the community pledge:

Here is the design: https://www.figma.com/file/eT5hwXGEM1gKasupZMepLK/Tally-Website?node-id=2931%3A92208

Gluz has include the main design (left) and a version with hover effect (right)

(normal)
![Screen Shot 2022-08-17 at 3 59 30 PM](https://user-images.githubusercontent.com/7005061/185231611-05c6f636-50e7-4d83-9200-8e319452856a.png)

(hover)
![Screen Shot 2022-08-17 at 3 59 36 PM](https://user-images.githubusercontent.com/7005061/185231613-711689e9-8724-4fb3-a1ca-de7f3f1c0d8d.png)

**Comment by cairomassimo** [comment]
Fixed in d16528f4b92de8b263b848707402cc299d3a102c and 38cc8b76726425aab92d3fd5b14be69d85f5cade.

I didn't implement the hover state yet. They are missing in the whole site, so it would make sense to implement them all contextually. Let me know what to do here @Gluzman @mr-michael.
