### ISSUE TITLE
Petition - not able to SIWE

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#69]
I'm able to connect my wallet, but not able to SIWE

Screens:

![Screen Shot 2022-08-15 at 5 29 39 PM](https://user-images.githubusercontent.com/7005061/184722016-8e507a3d-d6e3-43e3-8109-7e7186b61063.png)

![Screen Shot 2022-08-15 at 5 29 44 PM](https://user-images.githubusercontent.com/7005061/184722029-8c61ecca-a331-45e6-b0e5-7a84f0d72dbf.png)

![Screen Shot 2022-08-15 at 5 29 50 PM](https://user-images.githubusercontent.com/7005061/184722039-9e924648-6160-48c5-9589-0d80e8c31e8f.png)

![Screen Shot 2022-08-15 at 5 29 54 PM](https://user-images.githubusercontent.com/7005061/184722058-6f755d9f-21d3-4cab-af95-532c5f8302d3.png)

![Screen Shot 2022-08-15 at 5 29 57 PM](https://user-images.githubusercontent.com/7005061/184722076-43938603-c72f-4100-9292-fb927bf09786.png)

I can try to sign again, but it still returns this same error

**Comment by greg-nagy** [comment]
![CleanShot 2022-08-16 at 17 01 33](https://user-images.githubusercontent.com/7690112/184841330-32bf72fc-5424-457a-a931-6383645a3a9a.png)

siwe doesn't work with the version that's in the chrome store. You need to be on latest main. (I will create a release today)
