### ISSUE TITLE
Petition - add basic responsive styling

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#70]
Works great on desktop and tablet/ipad size, but styling breaks on phones.

It does not need to be perfect and this is low priority, but it'd be good to adjust this later this week

![Screen Shot 2022-08-15 at 5 52 41 PM](https://user-images.githubusercontent.com/7005061/184724801-f5a6098d-85fe-4d42-96cc-ca98d4d240c0.png)

**Comment by cairomassimo** [comment]
Fixed by 4b39e957ff7685d0686e17d1996fa45a14614132
