### ISSUE TITLE
Petition - Update body text of petition

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#72]
Updated language here:

https://docs.google.com/document/d/1KAu6dtEExajrXTXM8-vs1vFDhO3W8yrZk7bcnkl6CME/edit?usp=sharing

**Comment by greg-nagy** [comment]
Closed with https://github.com/tallycash/tally.cash/pull/67/commits/c53068084ae6562891e37ee34ba05bd21be29857
