### ISSUE TITLE
Petition - CTA updates

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#73]
![image](https://user-images.githubusercontent.com/7005061/184954188-d4a4001e-7520-4a09-8fd3-52a2673a3749.png)

- [x] " **Sign the Tally Ho Community Pledge** "

- [x] "Sign to join our community & be eligible for future surprises 👀"

(Also: 
- [x]  "signatures" --> "Signatures"
- [x]   "Sign now" --> "Sign Now")

![image](https://user-images.githubusercontent.com/7005061/184954450-5ba2e11b-b22c-4835-be58-e291e8ab4835.png)

**Are you in?** 
- [x]  "Receive a special discord role + a surprise later" --> "Good things come to those who sign 🙌"

- [x]   "Sign now" --> "Sign Now"

![image](https://user-images.githubusercontent.com/7005061/184958254-5fcba688-5447-462d-a18b-e80aa52c08d3.png)

- [x] "Download Tally Ho! wallet and sign this to show you’re onboard." --> "Download Tally Ho to sign our Community Pledge."

![image](https://user-images.githubusercontent.com/7005061/184954657-d1049df3-f561-49fa-b3b7-9ffdd0d4295a.png)

- [x]  "Sign this with your Tally Ho! wallet to show you’re onboard." --> "Sign the Tally Ho Community Pledge in 3 easy steps."

![image](https://user-images.githubusercontent.com/7005061/184954830-8d2434ba-60e6-4aa6-addb-9b89bc24796b.png)

- [x]  "Post on twitter to prove that you signed this" --> "Tweet your signature to be eligible for future surprises."

![image](https://user-images.githubusercontent.com/7005061/184954952-0960cd62-b71f-43f6-9f3d-ef45ada06cad.png)

- [x] --> " **Welcome to the community!** "
- [x] --> "You can now tweet your signature and claim the special 🔏**Verified Signer** role in our Discord! 👇"

![image](https://user-images.githubusercontent.com/7005061/184955065-542ac34c-f15b-4cd2-813c-90917082c684.png)

- [x]  "Share your values on Twitter" --> "Tweet your signature to be eligible for future surprises."

- [x]  "Sign-in with Discord to receive a special role in our community" --> "Claim your 🔏Verified Signer role to get full, verified access to our Discord."

- [x]  "🌭 Get full access to all the hot parts of our discord!"  --> (You'll need to [join our Discord](https://chat.tally.cash/) first.) [this should open Discord invite link on new tab(!)]

- [x]  "Twitter and Discord accounts will not be linked to your ethereum address" --> "Your Twitter and Discord accounts will NOT be linked to your Ethereum address."

**Comment by greg-nagy** [comment]
Closed via https://github.com/tallycash/tally.cash/pull/67/commits/f15811cd188382a223d56e2c8c6535a0daf80973
