### ISSUE TITLE
Petition - update Twitter card & page title

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#75]
Our current preview for the petition dapp preview looks like this:

![Screen Shot 2022-08-17 at 3 55 22 PM](https://user-images.githubusercontent.com/7005061/185231175-c1bee637-bade-4028-a782-01b63e4756ed.png)

Can we please update twitter card / preview for petition dapp page:
https://www.figma.com/file/eT5hwXGEM1gKasupZMepLK/Tally-Website?node-id=2997%3A102071

Title / subext should be updated to:

Page title - “Tally Ho Community Pledge”
Subtext - Sign to join our community & be eligible for future surprises

slug - web3pledge (in prod, it will be: tally.cash/web3pledge)

Can we pelase also update the Twitter card / preview for every other page on tally.cash from the current image to:
https://www.figma.com/file/eT5hwXGEM1gKasupZMepLK/Tally-Website?node-id=2590%3A86120

**Comment by cairomassimo** [comment]
Should be fixed in 84b3aa9d840d0e0a8d7cf248018e0671e1f78957, but it's not easy to test locally.
Leaving the issue open until tested (either locally with some tricks or after production deploy).

**Comment by greg-nagy** [comment]
![CleanShot 2022-08-23 at 18 14 01](https://user-images.githubusercontent.com/7690112/186133189-19bb55c3-e51c-4afe-961e-994dad32764c.png)

https://tally.cash/web3pledge/
