### ISSUE TITLE
Petition - Misc / small copy updates

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#76]
![Screen Shot 2022-08-17 at 4 54 59 PM](https://user-images.githubusercontent.com/7005061/185241347-0c1ace99-7e1a-46a3-8270-0d78ffbe12a0.png)

![Screen Shot 2022-08-17 at 4 54 56 PM](https://user-images.githubusercontent.com/7005061/185241348-8ede0656-96a2-4a43-a548-17657f125dbd.png)

- [x] "web3" --> "Web3"

![Screen Shot 2022-08-17 at 4 55 58 PM](https://user-images.githubusercontent.com/7005061/185241518-4c5b8c2c-7010-4787-a9d0-13d7ae134f64.png)

- [x] The styling of this paragraph above... needs to match the other paragraphs, example:

![Screen Shot 2022-08-17 at 4 56 05 PM](https://user-images.githubusercontent.com/7005061/185241600-0d4dc359-7c8d-4281-96a8-32644323f241.png)

...

![Screen Shot 2022-08-17 at 4 57 10 PM](https://user-images.githubusercontent.com/7005061/185241680-ecbc21c8-a632-40f0-994b-9f25a04e015b.png)

- [x] delete extra " after 🙌 

![Screen Shot 2022-08-17 at 4 44 17 PM](https://user-images.githubusercontent.com/7005061/185239547-4e847e2c-4e2f-4cc9-be2f-bc151135e628.png)

- [x] --> “Sign-In with Ethereum”

![Screen Shot 2022-08-17 at 4 45 09 PM](https://user-images.githubusercontent.com/7005061/185239648-6e92dd55-18ae-4036-956a-1df64d051c7f.png)

- [x] * “Signing in...”
- [x] “Waiting for sign-in”

![Screen Shot 2022-08-17 at 4 45 51 PM](https://user-images.githubusercontent.com/7005061/185239789-94b3bc52-1461-4705-a488-99b7d3326eb6.png)

- [x] "Sign Pledge"

**Comment by cairomassimo** [comment]
Also changed "Sign in with Discord" to "Sign-In with Discord".
