### ISSUE TITLE
Petition - update error message font color

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#78]
On error messages below, let's please update text color to hex: FE0466

![Screen Shot 2022-08-17 at 5 20 50 PM](https://user-images.githubusercontent.com/7005061/185245578-0b56f4be-9c8f-4b1a-9670-6b7ada23af98.png)

![Screen Shot 2022-08-17 at 5 21 06 PM](https://user-images.githubusercontent.com/7005061/185245579-f392cb46-3f12-44ea-b1bf-0916ce1177b9.png)

![Screen Shot 2022-08-17 at 5 21 08 PM](https://user-images.githubusercontent.com/7005061/185245580-e74a2edf-74c6-421f-aab8-267ba5be260b.png)

**Comment by cairomassimo** [comment]
Note: `#FE0466` is not among color styles in Figma.
