### ISSUE TITLE
Petition - update signing block graphic

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#79]
![Screen Shot 2022-08-21 at 11 14 28 PM](https://user-images.githubusercontent.com/7005061/185831509-e941cfa1-8892-413c-845d-846b4dad6665.png)

- [ ] Can we please replace the Discord logo with a Twitter logo

- [ ] Can we please update the ~identicon graphic on the right of the signing box

Right now some users I've shared this with are confused about what this means or does... My thought is we can either change it to be a "🎉" graphic (in which case maybe the order should be Twitter logo... Discord logo... then 🎉  or 🎁?--your call). - OR - some kind of graphic that tells the user they have joined the community and/or are helping defend eth/web3.

**Comment by mr-michael** [comment]
even the extension logo / token icon (dog face with * on orange background) could work well here

**Comment by VladUXUI** [comment]
@cairomassimo 

Here is the graphic that needs to change. Kept the same name+size

![intro](https://user-images.githubusercontent.com/80846886/185863270-7361fd4f-8964-48d9-bd8d-c57ba9da7109.png)

**Comment by cairomassimo** [comment]
Done!
