### ISSUE TITLE
Petition - TH not recognized as already installed when not default and side by side with MM

### ISSUE THREAD

**Issue by Naxsun** [tallycash/tally.cash#82]
When Tally Ho is installed side by side to MetaMask, and is not the default wallet, a user is prompted to install Tally Ho.

**Ideally**: We'd allow the user to connect
**If not possible:** Add a note to make users aware to set Tally Ho to default

**Comment by 0xDaedalus** [comment]
https://user-images.githubusercontent.com/94649004/185999407-1707c83c-ea9a-48a9-8d78-dd953be05679.mov

**Comment by mr-michael** [comment]
fwiw, if I have Tally Ho installed and no MetaMask, I am able to sign without issue.

**Comment by mr-michael** [comment]
Per @Naxsun's suggestion, we can add this message:

"If you already have Tally Ho, go to Settings and make sure it's set as your default wallet."

Can go right below the CTA

![Screen Shot 2022-08-22 at 6 06 25 PM](https://user-images.githubusercontent.com/7005061/186027152-d346d854-836c-44e0-99a1-477c737c8bfb.png)

This is an acceptable workaround if we can't fix this before Wednesday... but it's a bad look (it looks like we are forcing people to set our wallet as the default) so we should get a fix in here ASAP if possible

**Comment by greg-nagy** [comment]
Closed by https://github.com/tallycash/tally.cash/commit/62f5e023c19d4a4cf4b1be4c1c09f7f3be165362
