### ISSUE TITLE
Petition - Final(!) copy updates

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#88]
https://docs.google.com/document/d/1g_BT46FckLfhSK1t3gw_B9zwPd8mUjaM6uWBvYrsTlA/edit#

Changes:

- Some small tweaks are visible as 'suggestions' (in colored font)
- Let's please add a few links to open in new tabs(!)
- The last paragraph ("These are your rights as a citizen of Web3...") has been rewritten and now has a section title

**Comment by cairomassimo** [comment]
Done!
