### ISSUE TITLE
Petition - Update error copy on SIWE

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#89]
![Screen Shot 2022-08-22 at 6 03 05 PM](https://user-images.githubusercontent.com/7005061/186027478-61228d91-c4cd-4a49-b858-a324914b234a.png)

--> "Sign-in failed. Make sure you've set your Network to Ethereum."

**Comment by greg-nagy** [comment]
Done in https://github.com/tallycash/tally.cash/commit/7ec73a5bf1fc59a8f9ab1ffd677c2916ef0dbdca
