### ISSUE TITLE
Petition - Missing link styling

### ISSUE THREAD

**Issue by mr-michael** [tallycash/tally.cash#91]
We now have 4 links added to our Community Pledge (which is awesome), but you can't tell they're there! 

Can we please update them to "rgb(239 156 50)" or another color/style if @VladUXUI prefers?

![Screen Shot 2022-08-23 at 11 07 36 AM](https://user-images.githubusercontent.com/7005061/186194533-f9d81019-1891-4a96-a99b-d7bea7cb1241.png)

![Screen Shot 2022-08-23 at 11 07 39 AM](https://user-images.githubusercontent.com/7005061/186194534-8cd9b945-b151-46f7-9592-0744e9659122.png)

**Comment by cairomassimo** [comment]
Done. Hover state is still missing (@VladUXUI)
